name: DartExamples
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: dohlen.nick <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: ^4.0.0
  test_coverage: ^0.2.0
  random_string: ^0.0.2
